EmprestimoLivros/EmprestimoLivros/Models/EmprestimoModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmprestimoLivros.Models
{
    public class EmprestimoModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Digite o Nome do Recebedor! ")]
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "Digite o Nome do Fornecedor! ")]
        public string Fornecedor { get; set; }

        [Required(ErrorMessage = "Digite o Nome do Livro! ")]
        public string LivroEmprestado { get; set; }

        public DateTime DataUltimaAtualizacao { get; set; } = DateTime.Now;
    }
}

EmprestimoLivros/EmprestimoLivros/Models/ErrorViewModel.cs
namespace EmprestimoLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmprestimoLivros/EmprestimoLivros/Controllers/EmprestimoController.cs
using ClosedXML.Excel;
using EmprestimoLivros.Data;
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace EmprestimoLivros.Controllers
{
    public class EmprestimoController : Controller
    {
        //puxando a classe que ja esta conectada com o banco
        readonly private ApplicationDbContext _db; // o underline e pq e padrao de nomenclatura para propiedades privadas

        //construtor
        public EmprestimoController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            IEnumerable<EmprestimoModel> emprestimos = _db.Emprestimos; // pegando a tabela do banco
            return View(emprestimos);
        }

        [HttpGet] // quando tem isso e GET
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpGet]// quando tem isso e GET
        public IActionResult Editar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id); // esse codigo e igual a um select com where (select * from table where id = id enviado

            if (emprestimo == null)
            {
                return NotFound();
            }


            return View(emprestimo);
        }

        [HttpGet]

        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id); // esse codigo e igual a um select com where (select * from table where id = id enviado

            if (emprestimo == null)
            {
                return NotFound();
            }


            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Exportar()
        {
            var dados = GetDados();

            using (XLWorkbook workbook = new XLWorkbook()) // usansado using pois queremos criar essa operacao utilizar ela e desaparecer com ela ,se nao usar using ela fica aberta
            {
                workbook.AddWorksheet(dados, "Dados Emprestimos");

                using (MemoryStream ms = new MemoryStream())
                {
                    workbook.SaveAs(ms);
                    return File(ms.ToArray(), "application/vnd.openxmlformats-officedocument.spredsheetml.sheet", "Empestimos.xls");
                }
            }
        }

        private DataTable GetDados() //esta privado pois apenas o metodo a cima vai utilizar esse de baixo
        {
            DataTable dataTable = new DataTable();

            dataTable.TableName = "Dados Emprestimos";
            dataTable.Columns.Add("Id", typeof(int));
            dataTable.Columns.Add("Recebedor", typeof(string));
            dataTable.Columns.Add("Fornecedor", typeof(string));
            dataTable.Columns.Add("Livro", typeof(string));
            dataTable.Columns.Add("Data Emprestimo", typeof(DateTime));

            var dados = _db.Emprestimos.ToList();
            if (dados.Count > 0)
            {
                dados.ForEach(emprestimos => dataTable.Rows.Add(emprestimos.Id, emprestimos.Recebedor, emprestimos.Fornecedor, emprestimos.LivroEmprestado, emprestimos.DataUltimaAtualizacao));
            }


            return dataTable;
        }


        [HttpPost] // quando tem isso e POST
        public IActionResult Cadastrar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Add(emprestimo);
                _db.SaveChanges();

                TempData["MessagemSucesso"] = "Cadastro Realizado com Sucesso!!";

                return RedirectToAction("Index"); // depois que tudo der certo manda o usuario para a view INDEX
            }
            TempData["MessagemErro"] = "Algo deu errado, Nenhuma alteracao Foi realizada!!!";
            return View();
        }

        [HttpPost]
        public IActionResult Editar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Update(emprestimo);
                _db.SaveChanges();

                TempData["MessagemSucesso"] = "Cadastro Editado com Sucesso!!";

                return RedirectToAction("Index");
            }
            TempData["MessagemErro"] = "Algo deu errado, Nenhuma alteracao Foi realizada!!!";
            return View(emprestimo);
        }

        [HttpPost]

        public IActionResult Excluir(EmprestimoModel emprestimo)
        {
            if (emprestimo == null)
            {
                TempData["MessagemErro"] = "Algo deu errado, Nenhuma alteracao Foi realizada!!!";
                return NotFound();
            }

            _db.Emprestimos.Remove(emprestimo);
            _db.SaveChanges();

            TempData["MessagemSucesso"] = "Cadastro Excluido com Sucesso!!";
            return RedirectToAction("Index");
        }


    }
}

EmprestimoLivros/EmprestimoLivros/Controllers/HomeController.cs
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmprestimoLivros/EmprestimoLivros/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimoModel

@{
    ViewData["title"] = "Cadastrar Emprestimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro Emprestimos</h1>
    </div>
<form method="post" asp-asp-controller="Emprestimo" asp-action="Cadastrar">


    <div class="mb-3">
        <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está Recebendo o livro??">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
    </div>


    <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está Fornecendo o Livro??" >
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
    </div>

    <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro emprestado??">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
    </div>

    <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50 text-light"><i class="bi bi-plus-circle"></i> Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
    </div>

    


</form>
</div>

EmprestimoLivros/EmprestimoLivros/Views/Emprestimo/Editar.cshtml
@model EmprestimoModel

@{
    ViewData["title"] = "Editar Emprestimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Ediçao Emprestimos</h1>
    </div>
    <form method="post" asp-asp-controller="Emprestimo" asp-action="Editar">
        <input type="hidden" asp-for=Id />

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está Recebendo o livro??">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está Fornecendo o Livro??">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro emprestado??">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50 text-light">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>




    </form>
</div>

EmprestimoLivros/EmprestimoLivros/Views/Emprestimo/Excluir.cshtml
@model EmprestimoModel

@{
    ViewData["title"] = "Excluir Emprestimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Excluir Emprestimos</h1>
    </div>
    <form method="post" asp-asp-controller="Emprestimo" asp-action="Excluir">
        <input type="hidden" asp-for=Id />

        <h2 class="text-light text-center">Tem certeza que deseja excluir o resgistro abaixo ?</h2>

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está Recebendo o livro??" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está Fornecendo o Livro??" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro emprestado??" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>




    </form>
</div>

EmprestimoLivros/EmprestimoLivros/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimoModel>

<div class="container"> 

    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Emprestimos</h1>
        <div>
            <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Exportar"><i class="bi bi-file-earmark-spreadsheet"></i> Exportar</a>
            <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar"><i class="bi bi-plus-circle"></i> Cadastrar novo emprestimo</a>
        </div>

    </div>


    @if (TempData["MessagemSucesso"] != null)
    {
        <div class="alert-success text-light" role="alert">
            @TempData["MessagemSucesso"]
        </div>
    }
    @if (TempData["MessagemErro"] != null)
    {
        <div class="alert-danger text-light" role="alert">
            @TempData["MessagemErro"]
        </div>
    }


<table id="Emprestimos" class="table table-hover">
    <thead>
        <tr>
            <th></th>
            <th scope="col">Recebedor</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Livro</th>
            <th scope="col">Ultima Atualizacao</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var emprestimo in Model)
            {
                <tr>
                    <td>@emprestimo.Id</td>
                    <th scope="row">@emprestimo.Recebedor</th>
                    <td>@emprestimo.Fornecedor</td>
                    <td>@emprestimo.LivroEmprestado</td>
                    <td>@emprestimo.DataUltimaAtualizacao</td>
                    <td> <a asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2"><i class="bi bi-pen-fill"></i> Editar</a>
                     <a asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i> Excluir</a> </td>
                </tr>
            }

        }
    </tbody>
</table>
</div>

EmprestimoLivros/EmprestimoLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Emprestimos Online</h1>
    <p>Abra um livro, deixe-se levar.</p>
    <div>
        <img src="/img/5837138.png"
    </div>
</div>

EmprestimoLivros/EmprestimoLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Emprestimo Livros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoLivros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light " asp-area="" asp-controller="Home" asp-action="Index">Emprestimo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-book-fill"></i> Emprestimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-light">
            &copy; 2024 - EmprestimoLivros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>